In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# Definir dataset
y = np.array([78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4])
y1 = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1])
x1 = np.array([7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10])
x2 = np.array([26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68])
x3 = np.array([6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8])
x4 = np.array([60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12])

# Definir matrix
matriz = {'y1': y1, 'x1': x1, 'x2': x2, 'x3': x3, 'x4': x4}
df = pd.DataFrame(matriz)
x = df
# Agregar unos = np.ones((x.shape[0],x))
# unos = np.ones(13)
# unos = np.ones((x.shape[0],1))
print(x)
print(y)

# Formula general Beta=[[X'* x]^-1]*x*y
# Calculo de Matrix transpuesta X'
Xtranspuesta = x.T
print(Xtranspuesta)

# Calculo de Matrix transpuesta [X'* x]
XTX = np.dot(Xtranspuesta, x)
print(XTX)

# Calculo de Matrix inversa [X'* x]^-1
XTXinv = np.linalg.pinv(XTX)

# perform the dot product of XTXinv and Xtranspuesta, then multiply the result by y
Beta=np.dot(np.dot(XTXinv, Xtranspuesta), y)
print(Beta)






    y1  x1  x2  x3  x4
0    1   7  26   6  60
1    1   1  29  15  52
2    1  11  56   8  20
3    1  11  31   8  47
4    1   7  52   6  33
5    1  11  55   9  22
6    1   3  71  17   6
7    1   1  31  22  44
8    1   2  54  18  22
9    1  21  47   4  26
10   1   1  40  23  34
11   1  11  66   9  12
12   1  10  68   8  12
[ 78.5  74.3 104.3  87.6  95.9 109.2 102.7  72.5  93.1 115.9  83.8 113.3
 109.4]
    0   1   2   3   4   5   6   7   8   9   10  11  12
y1   1   1   1   1   1   1   1   1   1   1   1   1   1
x1   7   1  11  11   7  11   3   1   2  21   1  11  10
x2  26  29  56  31  52  55  71  31  54  47  40  66  68
x3   6  15   8   8   6   9  17  22  18   4  23   9   8
x4  60  52  20  47  33  22   6  44  22  26  34  12  12
[[   13    97   626   153   390]
 [   97  1139  4922   769  2620]
 [  626  4922 33050  7201 15739]
 [  153   769  7201  2293  4628]
 [  390  2620 15739  4628 15062]]
[62.40536931  1.55110265  0.51016758  0.1019094  -0.14406103]
